name: joix
description: A versatile dart validation library for expressive and fluent data schema validation
version: 2.0.0
repository: https://github.com/siddhantPanchal/joix

environment:
  sdk: ^3.1.0

dependencies:
  intl: ^0.19.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
